# Generated by Django 3.1.7 on 2021-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210416_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='thal',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Fixed Defect'), (2, 'Revesable Defect')]),
        ),
    ]
