# Generated by Django 3.1.7 on 2021-04-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210416_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], max_length=10),
        ),
    ]
