# Generated by Django 3.1.7 on 2021-04-17 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_test_result_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='ca',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default='Normal'),
        ),
        migrations.AlterField(
            model_name='test',
            name='chol',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='cp',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default='None'),
        ),
        migrations.AlterField(
            model_name='test',
            name='exang',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
        migrations.AlterField(
            model_name='test',
            name='oldpeak',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Abnormal')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], default='Female'),
        ),
        migrations.AlterField(
            model_name='test',
            name='slope',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='thal',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Fixed Defect'), (2, 'Reversable Defect')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='test',
            name='thalach',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='trestbps',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
        ),
    ]
