# Generated by Django 3.1.7 on 2021-04-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210417_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'User Test', 'verbose_name_plural': 'User Tests'},
        ),
        migrations.AlterField(
            model_name='test',
            name='slope',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default='0.0-0.2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='thal',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Fixed Defect'), (2, 'Reversible Defect')], default='Normal'),
        ),
    ]
