# Generated by Django 3.1.7 on 2021-05-01 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210426_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.AlterField(
            model_name='test',
            name='oldpeak',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='slope',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='thal',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Fixed Defect'), (2, 'Reversable Defect')], default='Normal'),
        ),
    ]
